### ISSUE TITLE
[20:07:42] [Server thread/CRITICAL]: ErrorException: "imagesy() expects parameter 1 to be resource, string given" (EXCEPTION) in "D:/PC/Desktop/mc/PocketMine-MP/virions/skinapi-master/src/xenialdan/skinapi/API" at line 214

### ISSUE THREAD

**Issue by rjworks** [thebigsmileXD/skinapi#1]
$player->setSkin(\xenialdan\skinapi\API::fromImage($this->plugin->getDataFolder()."skin.png"));
How do I set player's skin to the image I  have which is skin.png?

**Comment by inxomnyaa** [comment]
fromimage uses an image loaded via imgcreate or similar
Use the correct method, i think its 1 function below it

**Comment by inxomnyaa** [comment]
loadimage it is
