### ISSUE TITLE
how to use getHead to store it and use it later.

### ISSUE THREAD

**Issue by rjworks** [thebigsmileXD/skinapi#2]
how to use getHead to store it and use it later? how can i set player's head to mob head?

**Comment by inxomnyaa** [comment]
mob head: use a player head plugin. Those use custom geometry to create "fake" head entities since setting the texture directly does not work on mcpe.

store it: save to a path as png or just cache the image inside a variable

**Comment by rjworks** [comment]
> mob head: use a player head plugin. Those use custom geometry to create "fake" head entities since setting the texture directly does not work on mcpe.
> 
> store it: save to a path as png or just cache the image inside a variable

it's not possible to set mob head skin in chest?
